### 0. Setup

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor,AdaBoostRegressor, GradientBoostingRegressor, AdaBoostClassifier
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.model_selection import ParameterGrid
import time

### 1. Load Dataset

In [40]:
# Load the dataset
df = pd.read_csv(r"F:/Ironhack/ML_Project\data\bank-full-preprocessed.csv", sep=",")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,...,y,total_contacts,has_previous_contact,pdays_category,has_any_loan,age_group,month_num,month_sin,month_cos,balance_log
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,...,0,1,0,no_previous,1,55-64,5,0.5,-0.866025,7.670429
1,44,technician,single,secondary,no,29,yes,no,unknown,5,...,0,1,0,no_previous,1,35-44,5,0.5,-0.866025,3.401197
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,...,0,1,0,no_previous,1,25-34,5,0.5,-0.866025,1.098612
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,...,0,1,0,no_previous,1,45-54,5,0.5,-0.866025,7.317876
4,33,unknown,single,unknown,no,1,no,no,unknown,5,...,0,1,0,no_previous,0,25-34,5,0.5,-0.866025,0.693147

## 2. Encoding & Train/Test Split

Use `ColumnTransformer` + `OneHotEncoder` for categoricals; pass-through numerics.
We **stratify** by `y` due to class imbalance.

In [41]:
y = df['y']
X = df.drop(columns=['y'])
numeric_features = X.select_dtypes(include=['int64','float64','Int64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object','category','bool']).columns.tolist()

preprocess = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features),
        ('num', MinMaxScaler(), numeric_features)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train_proc = preprocess.fit_transform(X_train)
X_test_proc  = preprocess.transform(X_test)

ohe = preprocess.named_transformers_['cat'] if categorical_features else None
cat_names = (ohe.get_feature_names_out(categorical_features) if ohe is not None else np.array([]))
feature_names = np.concatenate([cat_names, np.array(numeric_features)])

pd.DataFrame(X_train_proc, columns=feature_names).head()

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,campaign,pdays,previous,total_contacts,has_previous_contact,has_any_loan,month_num,month_sin,month_cos,balance_log
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.2,0.0,0.0,0.2,0.0,0.0,0.636364,0.066987,0.250000,0.936690
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.6,0.0,0.0,0.6,0.0,0.0,0.272727,0.933013,0.250000,1.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.6,0.0,0.0,0.6,0.0,1.0,0.636364,0.066987,0.250000,0.879418
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.545455,0.250000,0.066987,0.628967
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.636364,0.066987,0.250000,0.881772

### 4. Modeling

In [42]:
def evaluate_model(model, X_train_proc, y_train, X_test_proc, y_test):
    """Train model and return key metrics."""
    model.fit(X_train_proc, y_train)
    y_pred = model.predict(X_test_proc)
    y_prob = model.predict_proba(X_test_proc)[:,1] if hasattr(model, "predict_proba") else None

    metrics = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob) if y_prob is not None else None
    }
    return metrics

In [43]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=300, random_state=42, class_weight="balanced"),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "AdaBoost": AdaBoostClassifier(random_state=42, algorithm="SAMME"),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42, scale_pos_weight=3)}

In [44]:
results = {}

for name, model in models.items():
    print(f"Training {name}...")
    metrics = evaluate_model(model, X_train_proc, y_train, X_test_proc, y_test)
    results[name] = metrics

# Convert to DataFrame for easy viewing
results_df = pd.DataFrame(results).T.sort_values(by="ROC-AUC", ascending=False)
print (results_df)

Training Logistic Regression...
Training Random Forest...
Training Gradient Boosting...
Training Decision Tree...
Training AdaBoost...
Training XGBoost...

f:\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [19:23:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

                     Accuracy  Precision    Recall        F1   ROC-AUC
Gradient Boosting    0.894504   0.652941  0.209830  0.317597  0.800075
XGBoost              0.882782   0.498950  0.448960  0.472637  0.789596
Random Forest        0.892845   0.619946  0.217391  0.321903  0.786855
Logistic Regression  0.769435   0.285416  0.645558  0.395827  0.777380
AdaBoost             0.893841   0.671329  0.181474  0.285714  0.764749
Decision Tree        0.840982   0.316602  0.310019  0.313276  0.610676

In [45]:
importances = pd.Series(models["Random Forest"].feature_importances_, index=feature_names)
importances.sort_values(ascending=False).head(10)

balance             0.103472
day                 0.100462
balance_log         0.098331
age                 0.098175
poutcome_success    0.040300
total_contacts      0.036124
campaign            0.035799
poutcome_unknown    0.025228
month_cos           0.024316
month_sin           0.024252
dtype: float64

In [46]:
importances = pd.Series(models["Gradient Boosting"].feature_importances_, index=feature_names)
importances.sort_values(ascending=False).head(10)

poutcome_success    0.402748
age                 0.082864
month_sin           0.064168
has_any_loan        0.056117
day                 0.049666
contact_unknown     0.043903
month_oct           0.040678
month_cos           0.035058
month_jun           0.033288
month_mar           0.027570
dtype: float64

In [47]:
coefs = pd.Series(models["Logistic Regression"].coef_[0], index=feature_names)
coefs.sort_values(ascending=False).head(10)

poutcome_success    1.657941
month_mar           1.217964
month_oct           0.837371
month_sep           0.708507
balance             0.660314
age_group_65+       0.634827
month_dec           0.526097
contact_cellular    0.487952
age_group_<25       0.393815
month_num           0.385750
dtype: float64

In [48]:
#importance from XGBoost
importances = pd.Series(models["XGBoost"].feature_importances_, index=feature_names)
importances.sort_values(ascending=False).head(10)

poutcome_success    0.296769
contact_unknown     0.091540
has_any_loan        0.059116
month_sin           0.032808
month_mar           0.032693
month_oct           0.028319
month_aug           0.023196
month_jun           0.018006
month_sep           0.017656
month_feb           0.016550
dtype: float32

#### 4.1 Grid Search

In [49]:
# Create stratified k-fold cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Define scoring metrics
scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

pipe = Pipeline([
    ("prep", preprocess),
    ("clf", None)
])

In [50]:
# Logistic Regression grid and base model
logreg_grid = {
    "clf": [LogisticRegression(max_iter=5000, solver="saga", class_weight="balanced", n_jobs=-1, random_state=42)],
    "clf__penalty": ["l2", "elasticnet"],
    "clf__C": [1.0, 0.5, 0.25, 0.1],
    "clf__l1_ratio": [0.0, 0.5, 0.9],
}

In [51]:
# Random Forest grid and base model
rf_grid = {
    "clf": [RandomForestClassifier(n_estimators=400, random_state=42, class_weight="balanced_subsample", n_jobs=-1)],
    "clf__max_depth": [None, 8, 12, 20],
    "clf__min_samples_split": [2, 10, 20],
    "clf__min_samples_leaf": [1, 3, 5],
    "clf__max_features": ["sqrt", "log2", 0.5],
}

In [52]:
# Gradient Boosting grid and base model
gb_grid = {
    "clf": [GradientBoostingClassifier(random_state=42)],
    "clf__n_estimators": [200, 400],
    "clf__learning_rate": [0.05, 0.1],
    "clf__max_depth": [2, 3, 4],
    "clf__subsample": [0.7, 1.0],
    "clf__max_features": [None, "sqrt"],
}

In [53]:
# Adjust scale_pos_weight based on class imbalance
neg, pos = (y_train == 0).sum(), (y_train == 1).sum()
spw = max(1.0, neg / max(1, pos))  # imbalance adjustment

# XGBoost grid and base model
xgb_base = XGBClassifier(
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    n_jobs=-1,
    random_state=42,
    scale_pos_weight=spw
)

xgb_grid = {
    "clf": [xgb_base],
    "clf__n_estimators": [300, 500],
    "clf__learning_rate": [0.05, 0.1, 0.2],
    "clf__max_depth": [3, 5, 7],
    "clf__subsample": [0.7, 1.0],
    "clf__colsample_bytree": [0.7, 1.0],
    "clf__min_child_weight": [1, 3, 5],
    "clf__reg_lambda": [1, 5, 10],
}

In [54]:
# Function to run grid search and display results
def run_grid(grid, name):
    gs = GridSearchCV(
        estimator=pipe,
        param_grid=grid,
        scoring=scoring,
        refit="roc_auc",
        cv=cv,
        n_jobs=-1,
        verbose=1,
        return_train_score=False
    )
    gs.fit(X_train, y_train)
    
    print(f"\n=== {name} — Best ROC-AUC: {gs.best_score_:.4f}")
    print("Best params:", gs.best_params_)
    
    y_pred = gs.predict(X_test)
    y_proba = gs.predict_proba(X_test)[:, 1]
    
    print("\nTest metrics:")
    print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision: {precision_score(y_test, y_pred):.4f}")
    print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
    print(f"F1:        {f1_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC:   {roc_auc_score(y_test, y_proba):.4f}")
    print("\nClassification report:\n", classification_report(y_test, y_pred))
    
    return gs

Run four models × multiple parameter combinations × cross-validation

In [55]:
#gs_logreg = run_grid(pipe, logreg_grid, "Logistic Regression")

In [56]:
# best parameters logistic regression
gs_logreg = {'clf': LogisticRegression(class_weight='balanced', max_iter=5000, n_jobs=-1,
                   random_state=42, solver='saga'), 'clf__C': 0.1, 'clf__l1_ratio': 0.9, 'clf__penalty': 'elasticnet'}

In [57]:
#gs_rf = run_grid(rf_grid, "Random Forest")

In [58]:
gs_rf = {'clf': RandomForestClassifier(class_weight='balanced_subsample', n_estimators=400,
                       n_jobs=-1, random_state=42), 'clf__max_depth': 12, 'clf__max_features': 'sqrt', 'clf__min_samples_leaf': 3, 'clf__min_samples_split': 20}

In [59]:
#gs_gb     = run_grid(gb_grid,     "Gradient Boosting")

In [60]:

gs_gb = {'clf': GradientBoostingClassifier(random_state=42), 'clf__learning_rate': 0.05, 'clf__max_depth': 4, 'clf__max_features': None, 'clf__n_estimators': 400, 'clf__subsample': 0.7}

In [61]:
#gs_xgb    = run_grid(xgb_grid,    "XGBoost")

In [62]:
gs_xgb    = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=3,
    min_child_weight=5,
    subsample=0.7,
    colsample_bytree=1.0,
    reg_lambda=5,
    eval_metric="auc",
    n_jobs=-1
)

In [63]:
#compare all best models
best_models = {
    "Logistic Regression": gs_logreg,
    "Random Forest": gs_rf,
    "Gradient Boosting": gs_gb,
    "XGBoost": gs_xgb
}
results_best = {}

for name, model in best_models.items():
    print(f"Evaluating {name}...")
    if isinstance(model, dict):
        # If model is a dict, extract the classifier
        clf = model['clf']
    else:
        clf = model
    metrics = evaluate_model(clf, X_train_proc, y_train, X_test_proc, y_test)
    results_best[name] = metrics
# Convert to DataFrame for easy viewing
results_best_df = pd.DataFrame(results_best).T.sort_values(by="ROC-AUC", ascending=False)
print (results_best_df)

Evaluating Logistic Regression...
Evaluating Random Forest...
Evaluating Gradient Boosting...
Evaluating XGBoost...
                     Accuracy  Precision    Recall        F1   ROC-AUC
XGBoost              0.895831   0.653439  0.233459  0.344011  0.807417
Gradient Boosting    0.894504   0.652941  0.209830  0.317597  0.800075
Random Forest        0.892735   0.620879  0.213611  0.317862  0.790576
Logistic Regression  0.768771   0.284881  0.646503  0.395490  0.777361

In [64]:
# importance from XGBoost
importances = pd.Series(gs_xgb.feature_importances_, index=feature_names)
importances.sort_values(ascending=False).head(5)

poutcome_success    0.231850
contact_unknown     0.092951
has_any_loan        0.069138
month_mar           0.041004
month_oct           0.038847
dtype: float32

### 5. Balance the target

In [65]:
# oversample the minority class using SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_proc, y_train)

In [66]:
# compare all best models on resampled data
best_models = {
    "Logistic Regression": gs_logreg,
    "Random Forest": gs_rf,
    "Gradient Boosting": gs_gb,
    "XGBoost": gs_xgb
}
results_resampled = {}
for name, model in best_models.items():
    print(f"Evaluating {name} on resampled data...")
    if isinstance(model, dict):
        # If model is a dict, extract the classifier
        clf = model['clf']
    else:
        clf = model
    metrics = evaluate_model(clf, X_train_res, y_train_res, X_test_proc, y_test)
    results_resampled[name] = metrics
# Convert to DataFrame for easy viewing
results_resampled_df = pd.DataFrame(results_resampled).T.sort_values(by="ROC-AUC", ascending=False)
print (results_resampled_df)

Evaluating Logistic Regression on resampled data...
Evaluating Random Forest on resampled data...
Evaluating Gradient Boosting on resampled data...
Evaluating XGBoost on resampled data...
                     Accuracy  Precision    Recall        F1   ROC-AUC
XGBoost              0.889638   0.546154  0.335539  0.415691  0.785373
Random Forest        0.885547   0.517190  0.327032  0.400695  0.784556
Gradient Boosting    0.879133   0.480534  0.408318  0.441492  0.780169
Logistic Regression  0.752073   0.267843  0.645558  0.378603  0.770752

In [67]:
# under sample the majority class using RandomUnderSampler
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_res_us, y_train_res_us = rus.fit_resample(X_train_proc, y_train)
# compare all best models on under-sampled data
best_models = {
    "Logistic Regression": gs_logreg,
    "Random Forest": gs_rf,
    "Gradient Boosting": gs_gb,
    "XGBoost": gs_xgb
}
results_under_sampled = {}
for name, model in best_models.items():
    print(f"Evaluating {name} on under-sampled data...")
    if isinstance(model, dict):
        # If model is a dict, extract the classifier
        clf = model['clf']
    else:
        clf = model
    metrics = evaluate_model(clf, X_train_res_us, y_train_res_us, X_test_proc, y_test)
    results_under_sampled[name] = metrics
# Convert to DataFrame for easy viewing
results_under_sampled_df = pd.DataFrame(results_under_sampled).T.sort_values(by="ROC-AUC", ascending=False)
print (results_under_sampled_df)

Evaluating Logistic Regression on under-sampled data...
Evaluating Random Forest on under-sampled data...
Evaluating Gradient Boosting on under-sampled data...
Evaluating XGBoost on under-sampled data...
                     Accuracy  Precision    Recall        F1   ROC-AUC
XGBoost              0.803163   0.328910  0.655955  0.438131  0.801737
Gradient Boosting    0.801393   0.324620  0.645558  0.432005  0.798484
Random Forest        0.783147   0.307627  0.682420  0.424082  0.792379
Logistic Regression  0.771536   0.286078  0.637051  0.394845  0.776617

In [68]:
# over sample the minority class using ADASYN
from imblearn.over_sampling import ADASYN
adasyn = ADASYN(random_state=42)
X_train_res_adasyn, y_train_res_adasyn = adasyn.fit_resample(X_train_proc, y_train)
# compare all best models on ADASYN resampled data
best_models = {
    "Logistic Regression": gs_logreg,
    "Random Forest": gs_rf,
    "Gradient Boosting": gs_gb,
    "XGBoost": gs_xgb
}
results_adasyn = {}
for name, model in best_models.items():
    print(f"Evaluating {name} on ADASYN resampled data...")
    if isinstance(model, dict):
        # If model is a dict, extract the classifier
        clf = model['clf']
    else:
        clf = model
    metrics = evaluate_model(clf, X_train_res_adasyn, y_train_res_adasyn, X_test_proc, y_test)
    results_adasyn[name] = metrics
# Convert to DataFrame for easy viewing
results_adasyn_df = pd.DataFrame(results_adasyn).T.sort_values(by="ROC-AUC", ascending=False)
print (results_adasyn_df)

Evaluating Logistic Regression on ADASYN resampled data...
Evaluating Random Forest on ADASYN resampled data...
Evaluating Gradient Boosting on ADASYN resampled data...
Evaluating XGBoost on ADASYN resampled data...
                     Accuracy  Precision    Recall        F1   ROC-AUC
XGBoost              0.890412   0.556114  0.313800  0.401208  0.782203
Random Forest        0.885215   0.515337  0.317580  0.392982  0.780750
Gradient Boosting    0.878248   0.475202  0.389414  0.428052  0.771862
Logistic Regression  0.709610   0.240225  0.685255  0.355741  0.768386

In [69]:
# random the sample the majority class using TomekLinks
from imblearn.under_sampling import TomekLinks
tl = TomekLinks()
X_train_res_tl, y_train_res_tl = tl.fit_resample(X_train_proc, y_train)
# compare all best models on TomekLinks resampled data
best_models = {
    "Logistic Regression": gs_logreg,
    "Random Forest": gs_rf,
    "Gradient Boosting": gs_gb,
    "XGBoost": gs_xgb
}
results_tomeklinks = {}
for name, model in best_models.items():
    print(f"Evaluating {name} on TomekLinks resampled data...")
    if isinstance(model, dict):
        # If model is a dict, extract the classifier
        clf = model['clf']
    else:
        clf = model
    metrics = evaluate_model(clf, X_train_res_tl, y_train_res_tl, X_test_proc, y_test)
    results_tomeklinks[name] = metrics
# Convert to DataFrame for easy viewing
results_tomeklinks_df = pd.DataFrame(results_tomeklinks).T.sort_values(by="ROC-AUC", ascending=False)
print (results_tomeklinks_df)

Evaluating Logistic Regression on TomekLinks resampled data...
Evaluating Random Forest on TomekLinks resampled data...
Evaluating Gradient Boosting on TomekLinks resampled data...
Evaluating XGBoost on TomekLinks resampled data...
                     Accuracy  Precision    Recall        F1   ROC-AUC
XGBoost              0.893509   0.594433  0.282609  0.383088  0.807104
Gradient Boosting    0.894615   0.620690  0.255198  0.361688  0.801977
Random Forest        0.891850   0.582988  0.265595  0.364935  0.790526
Logistic Regression  0.764238   0.281530  0.654064  0.393629  0.777296